name: IBM Cloud Auto Restart multi

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '05 12 * * *'

jobs:
  ibm-cloud-restart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        chmod -R 777 ./IBM_Cloud_CLI/
    - name: Login IBM Cloud
      env:
        REGION_NUM: ${{ secrets.REGION_NUM }}
      run: |
        IBM_ACCOUNT='${{ secrets.IBM_ACCOUNT_MULTI }}'
        IBM_ACCOUNT_PWD='${{ secrets.IBM_ACCOUNT_PWD_MULTI }}'        
        IBM_APP_NAME='${{ secrets.IBM_APP_NAME_MULTI }}'
        RESOURSE_ID='${{ secrets.RESOURSE_ID_MULTI }}'
        
        IBM_ACCOUNT_list=()
        IBM_ACCOUNT_PWD_list=()        
        IBM_APP_NAME_list=()
        RESOURSE_ID_list=()
        IFS=" "
        
        for u in ${IBM_ACCOUNT[*]}
        do
        IBM_ACCOUNT_list[${#IBM_ACCOUNT_list[*]}]=${u}
        done

        for r in ${IBM_ACCOUNT_PWD[*]}
        do
        IBM_ACCOUNT_PWD_list[${#IBM_ACCOUNT_PWD_list[*]}]=${r}
        done
        
        for p in ${IBM_APP_NAME[*]}
        do
        IBM_APP_NAME_list[${#IBM_APP_NAME_list[*]}]=${p}
        done
        
        for q in ${RESOURSE_ID[*]}
        do
        RESOURSE_ID_list[${#RESOURSE_ID_list[*]}]=${q}
        done
        
        IBM_ACCOUNT_num=${#IBM_ACCOUNT_list[*]}
        IBM_ACCOUNT_PWD_num=${#IBM_ACCOUNT_PWD_list[*]}        	
        IBM_APP_NAME_num=${#IBM_APP_NAME_list[*]}
        RESOURSE_ID_num=${#RESOURSE_ID_list[*]}
        
        if [ $IBM_ACCOUNT_num != $IBM_ACCOUNT_PWD_num ];then
             echo "IBM_ACCOUNT和IBM_ACCOUNT_PWD个数不对应"
             exit 1
        fi

        if [ $IBM_ACCOUNT_num != $IBM_APP_NAME_num ];then
             echo "IBM_ACCOUNT和IBM_APP_NAME个数不对应"
             exit 1
        fi
        
        if [ $IBM_ACCOUNT_num != $RESOURSE_ID_num ];then
             echo "IBM_ACCOUNT和RESOURSE_ID个数不对应"
             exit 1
        else
             echo "共有 $IBM_ACCOUNT_num 个账号，即将开始重启操作"
        fi        

        for ((i=0;i<$IBM_ACCOUNT_num;i++))
        do
        ./IBM_Cloud_CLI/ibmcloud login <<EOF
        ${IBM_ACCOUNT_list[$i]}
        ${IBM_ACCOUNT_PWD_list[$i]}
        if [ $i == 0 ];then
             $REGION_NUM
        fi     
        no
        EOF
        echo "${IBM_ACCOUNT_list[$i]} 登陆成功"

        ./IBM_Cloud_CLI/ibmcloud target -g "${RESOURSE_ID_list[$i]}"
        ./IBM_Cloud_CLI/ibmcloud target --cf
        if [ $i == 0 ];then
            ./IBM_Cloud_CLI/ibmcloud cf install        	
        fi 
        echo "${IBM_ACCOUNT_list[$i]} Target IBM Cloud 成功"

        ./IBM_Cloud_CLI/ibmcloud cf restart "${IBM_APP_NAME_list[$i]}"
        echo "${IBM_ACCOUNT_list[$i]} Restart IBM Cloud 成功"
        
        done
